language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - main

cache:
  directories:
    - node_modules
  yarn: true

before_install:
  - export TZ="Asia/Shanghai"

install:
  - yarn

script:
  - yarn blog:build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./sources/.vuepress/dist/
  target-branch: gh-pages
  verbose: true
  on:
    branch: main