name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist/
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: npm install && npm run docs:build
        # 进入生成的文件夹
        CD: cd docs/.vuepress/dist

        # 绑定自定义域名，根据个人实际域名修改。
        # 如果不需要绑定自定义域名，可将下面这行代码注释掉，例如博主的是www.honkerzhou.com
        ADD_CNAME: echo 'blog.landofdream.top' > CNAME
